#!/bin/bash

#Delete files related with simulation
pj="/mnt/vol_NFS_Zener/WD_ESPEC/disalazar/EM_Projects/MixedSignal/Asignacion2_SampleAndHold"

rm -rf ${pj}/genie.ign ${pj}/genie.log ${pj}/simv.daidir ${pj}/simv.msv ${pj}/sxcmd.log ${pj}/csrc ${pj}/simv ${pj}/top.log ${pj}/top.pvadir ${pj}/top.valog ${pj}/ucli.key ${pj}/swave_compile_done ${pj}/xavcs.vpd ${pj}/*~ 
rm -rf ${pj}/*.ic0* ${pj}/*.pa0* ${pj}/*.st0* ${pj}/*.tr0* ${pj}/sxcmd* ${pj}/*.ac0*
